### ISSUE TITLE
Changes to Gdn_Role structure cannot be referenced in 'where' clause without checking for its existence

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2809]
/utility/structure: "Unknown column 'Type' in 'where clause'" when attempting to update from version that doesn't have #2757.

**Comment by linc** [comment]
Unknown column 'Type' in 'where clause'
## /library/database/class.database.php(412)
#0 [internal function]: Gdn_ErrorHandler(256, 'Unknown column ...', '...', 412, Array)
#1 /library/database/class.database.php(412): trigger_error('Unknown column ...', 256)
#2 /library/database/class.sqldriver.php(1663): Gdn_Database->query('select *?from G...', Array, Array)
#3 //library/database/class.sqldriver.php(884): Gdn_SQLDriver->query('select *?from G...')
#4 /applications/dashboard/models/class.rolemodel.php(236): Gdn_SQLDriver->getWhere('Role', Array)
#5 /applications/dashboard/settings/structure.php(157): RoleModel::getAllDefaultRoles()
#6 /applications/dashboard/controllers/class.utilitycontroller.php(328): include('...')
#7 [internal function]: UtilityController->structure('all', '1', '0', '0')
#8 //library/core/class.dispatcher.php(329): call_user_func_array(Array, Array)
#9 /index.php(40): Gdn_Dispatcher->dispatch()
#10 {main}
