### ISSUE TITLE
Import error on load user step when MySQL Strict mode is enabled

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#4108]
Happen on the 'Load User Table' step.

```
Row 1 doesn't contain data for all columns
## /htdocs/vanilla/library/database/class.database.php(412)
#0 [internal function]: Gdn_ErrorHandler(256, 'Row 1 doesn't c...', '/Users/alexandr...', 412, Array)
#1 /htdocs/vanilla/library/database/class.database.php(412): trigger_error('Row 1 doesn't c...', 256)
#2 /htdocs/vanilla/library/database/class.sqldriver.php(1664): Gdn_Database->query('load data infil...', Array, Array)
#3 /htdocs/vanilla/applications/dashboard/models/class.importmodel.php(1651): Gdn_SQLDriver->query('load data infil...', 'select')
#4 /htdocs/vanilla/applications/dashboard/models/class.importmodel.php(1262): ImportModel->query('load data infil...')
#5 /htdocs/vanilla/applications/dashboard/models/class.importmodel.php(1227): ImportModel->_LoadTableOnSameServer('GDN_zUser', ''/Users/alexand...')
#6 /htdocs/vanilla/applications/dashboard/models/class.importmodel.php(1162): ImportModel->loadTable('User', '/Users/alexandr...')
#7 /htdocs/vanilla/applications/dashboard/models/class.importmodel.php(1596): ImportModel->loadUserTable()
#8 /htdocs/vanilla/applications/dashboard/controllers/class.importcontroller.php(56): ImportModel->runStep(3)
#9 /htdocs/vanilla/library/core/class.dispatcher.php(334): ImportController->go('wYWrbHMW9ohop8g...')
#10 /htdocs/vanilla/index.php(39): Gdn_Dispatcher->dispatch()
#11 {main}
```

**Comment by linc** [comment]
My recollection is we resolved all MySQL strict mode errors last year.

**Comment by tburry** [comment]
@vincentlam92, can you try importing with MySQL strict mode and see if this is still an issue?

**Comment by vincentlam92** [comment]
@tburry I dont really see this error while i import the db in vanilla.

**Comment by charrondev** [comment]
Removing the "Won't fix" label and calling it fixed.
