### ISSUE TITLE
[TravisCI] Random error 'Vanilla did not install'

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5470]
This is a follow up of https://github.com/vanilla/vanilla/pull/5445

You can see the error on that job: https://travis-ci.org/vanilla/vanilla/jobs/224308262
I was not able to reproduce it on my local setup.

Test stack trace
``` 
/home/travis/build/vanilla/vanilla/tests/APIv0/AltTest.php:43
2) VanillaTests\APIv0\SmokeTest
exception 'Exception' with message 'Vanilla did not install.' in /home/travis/build/vanilla/vanilla/tests/APIv0/APIv0.php:207
Stack trace:
#0 /home/travis/build/vanilla/vanilla/tests/APIv0/BaseTest.php(24): VanillaTests\APIv0\APIv0->install('VanillaTests\\AP...')
#1 [internal function]: VanillaTests\APIv0\BaseTest::setUpBeforeClass()
#2 /home/travis/build/vanilla/vanilla/vendor/phpunit/phpunit/src/Framework/TestSuite.php(668): call_user_func(Array)
#3 /home/travis/build/vanilla/vanilla/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#4 /home/travis/build/vanilla/vanilla/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#5 /home/travis/build/vanilla/vanilla/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(517): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#6 /home/travis/build/vanilla/vanilla/vendor/phpunit/phpunit/src/TextUI/Command.php(186): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array, true)
#7 /home/travis/build/vanilla/vanilla/vendor/phpunit/phpunit/src/TextUI/Command.php(116): PHPUnit_TextUI_Command->run(Array, true)
#8 /home/travis/build/vanilla/vanilla/vendor/phpunit/phpunit/phpunit(52): PHPUnit_TextUI_Command::main()
#9 {main}
```

Error stack trace
```
2017/04/21 14:24:12 [error] 2544#0: *15 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Table 'vanilla_test.GDN_UserRole' doesn't exist in /home/travis/build/vanilla/vanilla/library/database/class.database.php on line 421
Stacktrace [/home/travis/build/vanilla/vanilla/]:
- library/database/class.database.php:421 in trigger_error()
- library/database/class.sqldriver.php:1668 in Gdn_Database->query()
- library/database/class.sqldriver.php:888 in Gdn_SQLDriver->query()
- applications/dashboard/models/class.rolemodel.php:230 in Gdn_SQLDriver->getWhere()
- applications/dashboard/models/class.permissionmodel.php:514 in RoleModel::getDefaultRoles()
- applications/dashboard/models/class.usermodel.php:4545 in PermissionModel->cachePermissions()
- library/core/class.session.php:476 in UserModel->getPermissions()
- library/core/class.auth.php:59 in Gdn_Session->start()
- bootstrap.php:361 in Gdn_Auth->startAuthenticator()
- index.php:32 in require_once()" while reading response header from upstream, client: 127.0.0.1, server: testing-docker-df915e05-7084-4563-a4e1-fe101ac6feec, request: "POST /utility/update HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "vanilla.test:8080"
```

So the error is caused by the fact that [Gdn_Auth->startAuthenticator()](https://github.com/vanilla/vanilla/blob/ee6a18703440870e74706bb9cc19eb67d583c149/library/core/class.auth.php#L54) does not return early because `!c('Garden.Installed', false)` evaluates to false. That means that the config Garden.Installed is set to true "somehow".
My guess was that the config file was not cleaned properly so I made these fixes:

- Fix a case where the config wouldn't be deleted: 89eed50
- Make sure that the config is really deleted https://github.com/vanilla/vanilla/commit/7c69d78820d039b736b084a680dfc121f5bd02d9#diff-c5e9e680082815922f403c3d27a36181R385

No exception thrown...
I did way more debugging until I stumbled upon this [https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image](Troubleshooting-Locally-in-a-Docker-Image)
Nice!
But the two last steps are:
```
Manually install any dependencies.
Manually run your Travis CI build command.
```
GL on getting the same build environment!
There was an answer on StackOverflow that helped a bit though http://stackoverflow.com/questions/21053657/how-to-run-travis-ci-locally#answer-41935867

The only problem is that this tool travis-build does not really work properly with a .travis.yml even it if says it does. Was it really wants is a payload generated by another travis tool... The scheduler I think? I almost ended up installing all the travis-ci repository, that have almost no doc, and couldn't make them work properly. 

I decided to use travis-build and patch the holes!
You need to install docker beforehand (I also had to read the docker documentation since I did not know anything about it!)

```bash
# Skip these 2 on the first run
docker container stop travis-debug
docker container rm travis-debug
# Start the container and log in it!
docker run --name travis-debug -dit quay.io/travisci/travis-php /sbin/init
docker exec -it travis-debug bash -l
```

Then run this:
```bash
# You can change this and travis compile will generate a scritt that will intall travis' precompiled php version!
PHP_VERSION=5.6
# Set this to the branch you want to unit test!
BRANCH='master'

# Update some package
# Install nginx + realpath since "travis compile" does not parse the addon directive from .travis.yml...
export DEBIAN_FRONTEND=noninteractive
sudo -E apt-get -yq update &>> ~/apt-get-update.log \
    && sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install \
        libc-bin \
        libc-dev-bin \
        libc6-dev \
        nginx \
        realpath

# Make sure nginx can be started by travis
cat > /usr/local/bin/nginx <<- EOM
#!/bin/bash
sudo /usr/sbin/nginx "\$@"
EOM

chmod +x /usr/local/bin/nginx

# Log in as travis
su - travis

# Install a recent ruby (default is 1.9.3)
rvm install 2.3.0
rvm use 2.3.0

# Install travis-build to generate a .sh out of .travis.yml
cd builds
git clone https://github.com/travis-ci/travis-build.git
cd travis-build
gem install travis
yes | travis # to create ~/.travis
ln -s `pwd` ~/.travis/travis-build
bundle install

# Create project dir, assuming your project is `me/project` on GitHub
cd ~/builds
mkdir vanilla
cd vanilla
git clone https://github.com/vanilla/vanilla.git
cd vanilla

# Create the bash script to launch the unit test
travis compile > ci.sh

# Fix the branch since it is not properly detected even if you checkout it.
sed -i "s/--branch\\\\=\\\\'\\\\'/--branch\\\\=\\\\'$BRANCH\\\\'/g" ci.sh

# Fix the php version... again... .travis.yml is not properly parsed the the whole array of versions if taken...
phpversion=$(grep -Eo TRAVIS_PHP_VERSION=.+ ci.sh | grep -Eo "\[.+\]" | grep -Eo [^][]+);
ephpversion=$(printf '%q' $phpversion)
sed -i "s/\[$phpversion\]/$PHP_VERSION/g" ci.sh
ephpversion=$(sed -E 's/( |")/\\\\\1/g' <<< $phpversion)
sed -i "s/\\\\\[$ephpversion\\\\\]/$PHP_VERSION/g" ci.sh

# Make that script executable!
chmod +x ci.sh

. ci.sh
```

This is a mixin from the stackoverflow post and the job log of our travis builds.

Sadly this does not help at reproducing the error....

**Comment by initvector** [comment]
It would seem this has solved our problem: https://github.com/vanilla/vanilla/pull/5518
