### ISSUE TITLE
Saving Posting Settings toggles a different setting.

### ISSUE THREAD

**Issue by Charrondev** [vanilla/vanilla#5631]
Saving the settings on the posting settings page of the dashboard toggle the `Enable link embeds in discussions and comments` setting.

**To Reproduce:**

1. Go to `/vanilla/settings/posting` section of the dashboard.
2. Click save.

![may-30-2017 11-41-18](https://cloud.githubusercontent.com/assets/1770056/26591854/f189571e-452c-11e7-86ff-8a8235ad1533.gif)

The debug trace printed out is:

```
Undefined index: checked

#0 /www/spawn/library/core/class.form.php(612): Gdn_ErrorHandler(8, 'Undefined index...', '/www/spawn/libr...', 612, Array)
#1 /www/spawn/applications/vanilla/views/vanillasettings/posting.php(23): Gdn_Form->toggle('Garden.Format.D...', 'Enable link emb...', Array, 'Allow links to ...', true)
#2 /www/spawn/library/core/class.controller.php(696): include('/www/spawn/appl...')
#3 /www/spawn/library/core/class.controller.php(1231): Gdn_Controller->fetchView('', false, false)
#4 /www/spawn/library/core/class.pluggable.php(210): Gdn_Controller->xRender()
#5 /www/spawn/applications/vanilla/Controllers/class.vanillasettingscontroller.php(91): Gdn_Pluggable->__call('render', Array)
#6 /www/spawn/library/core/class.dispatcher.php(803): VanillaSettingsController->posting()
#7 /www/spawn/library/core/class.dispatcher.php(249): Gdn_Dispatcher->dispatchController(Object(Gdn_Request), Array)
#8 /www/spawn/index.php(39): Gdn_Dispatcher->dispatch()
#9 {main}
```

**Comment by linc** [comment]
This was reported in https://github.com/vanilla/vanilla/issues/5605 and closed by https://github.com/vanilla/vanilla/pull/5636 but your issue was much better. GIFs!
